"""Add last_read_at field in ConversationMember model

Revision ID: ff0161a82bea
Revises: 6d7b25532c43
Create Date: 2026-09-15 21:43:48.345774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0161a82bea'
down_revision: Union[str, Sequence[str], None] = '6d7b25532c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_member', sa.Column('last_read_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_member', 'last_read_at')
    # ### end Alembic commands ###
